name: Git Scan
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: actions/setup-go@v2.1.5
    steps:
      - run: git clone https://github.com/zricethezav/gitleaks.git
      - run: cd gitleaks && make build
      - run: gitleaks detect
      #- run: pip install detect-secrets
      #- run: detect-secrets scan --all-files
