name: Git Scan
on: [push]
jobs: 
  # The “build” workflow 
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14.0' # The Go version to download (if necessary) and use.
    
    # Install all the dependencies
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        
    # Run build of the application
    - name: Run build
      run: |
        go mod init 
        git clone https://github.com/zricethezav/gitleaks.git
        cd gitleaks && make build
        gitleaks detect
    
# jobs:
#   Explore-GitHub-Actions:
#     runs-on: actions/setup-go@v2.1.5
#     steps:
#       - run: git clone https://github.com/zricethezav/gitleaks.git
#       - run: cd gitleaks && make build
#       - run: gitleaks detect
#       #- run: pip install detect-secrets
#       #- run: detect-secrets scan --all-files
