name: Git Scan
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: zricethezav/gitleaks:latest
    steps:
      - run: gitleaks detect
      #- run: pip install detect-secrets
      #- run: detect-secrets scan --all-files
